name: GitHub Pages

on:
  push:
    branches: [ "master" ]

jobs:
  publish:

    runs-on: ubuntu-latest
    steps:
    - name: Build
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - run: npm i -g pnpm
    - run: pnpm i
    - run: pnpm run build
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
